version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Use the desired Python version

    steps:
      - checkout  # Checkout the code from GitHub

      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            ./Student-Registration-System-Django/studentreg/venv/Scripts/activate
            pip install -r ./studentreg/requirement.txt

      - run:
          name: Run tests
          command: |
            . ./venv/Scripts/activate
            pytest

workflows:
  version: 2
  build:
    jobs:
      - build
